### ISSUE TITLE
compile instructions

### ISSUE THREAD

**Issue by Marwe** [pa5cal/NoFlyMapForDronePilots#1]
Could you add compile and usage instructions?
I could not figure out how to build, install and use. 
The pom.xml seems to install fine with mavens `mvn install`, but I am missing something to run the result from commandline.

**Comment by pa5cal** [comment]
Sure. There you go: https://github.com/pa5cal/NoFlyMapForDronePilots/blob/master/README.md

**Comment by Marwe** [comment]
Thanks for adding the run instructions. I am still too stupid to get the dependencies at runtime right. Shouldn't the deps be handled/installed by maven? 
I get an osmosis related "not found" 
`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/openstreetmap/osmosis/core/task/v0_6/Sink`

mvn installed stuff to:
`~/.m2/repository/org/openstreetmap/osmosis`
Sink.class is in the jar osmosis-core-0.46.jar, adding this path with -cp does not help.

I even installed osmosis locally and included `-cp osmosis/lib/default` with no luck.
Can you elaborate on this for me = not-a-Java-developer? Getting java build frameworks and dependencies right without using the heavy IDE stuff is not for beginners ;)

**Comment by pa5cal** [comment]
Sorry, I made a mistake in the pom file. Totally forgot to add the build-element section.
Thank you very much for opening this issue! Now it should hopefully works as expected.
